.catalog:
  name: "mysql"
  version: "v5.6"
  description: "A recommended stack for the MySQL RDBMS."
  uuid: mysql-0
  minimum_rancher_version: v1.0.0

version: '2'
services:
  # mysql-lb:
  #   scale: 1
  #   start_on_create: true
  #   lb_config:
  #     certs: []
  #     port_rules:
  #     - protocol: tcp
  #       service: mysql
  #       source_port: ${mysql_lb_port}
  #       target_port: 3306
  #     - protocol: http
  #       service: adminer
  #       source_port: ${adminer_port}
  #       target_port: 8080
  #   health_check:
  #     healthy_threshold: 2
  #     response_timeout: 2000
  #     port: 42
  #     unhealthy_threshold: 3
  #     interval: 2000
  #     strategy: recreate
  mysql:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 3306
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  adminer:
    scale: 1
    start_on_create: true
