version: '2'
volumes:
  fileserver-data:
    driver: rancher-nfs

services:
  fileserver:
    image: registry.cn-shenzhen.aliyuncs.com/xuu/http-fileserver:0.0.1
    tty: true
    stdin_open: true
    volumes:
      - fileserver-data:/upload
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: fileserver-volume
    ports:
      - 8080